# Configuration should match devices in /sys/class/uio/ for dma/timers and
#   /sys/class/i2c-dev/ for i2c.
# NOTE: `cat` their `name` file to find the device type.
i2c_devs: [2, 3]
vdma_devs: [1, 0]
trigger_timer_dev: 3
line_count_timer_dev: 2
