# Configuration should match devices in /sys/class/uio/ for dma/timers and
#   /sys/class/i2c-dev/ for i2c.
# NOTE: `cat` their `name` file to find the device type.
cam_nums: [0, 1] # 4->cam5 6->cam0 10->cam1
i2c_devs: [6, 10] # 4->cam5 6->cam0 10->cam1
vdma_devs: [0, 1] # direct mapping
# If cameras are borked this should hang. If it passes straight through, the numbers are backwards.
trigger_timer_dev: 7
line_count_timer_dev: 6
primary_cam: 0
